issuer: https://token.actions.githubusercontent.com
subject_pattern: 'repo:sharing-fish/fish-platform-deploy:ref:refs/heads/main'

permissions:
  contents: read

repositories:
- fish-platform-library
