issuer: https://token.actions.githubusercontent.com
subject_pattern: 'repo:sharing-fish/fish-platform-library:ref:refs/heads/main'

permissions:
  contents: write
  packages: write
  metadata: read
  pull-requests: write

repositories:
- fish-platform-library
